<?php

namespace Database\Seeders;

use App\Models\LocationCity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocationCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['id' => 1, 'state_id' => 1, 'name' => 'La soukra'],
            ['id' => 2, 'state_id' => 1, 'name' => 'Menzah 6'],
            ['id' => 3, 'state_id' => 1, 'name' => 'Raoued'],
            ['id' => 4, 'state_id' => 1, 'name' => 'Sidi Thabet'],
            ['id' => 5, 'state_id' => 1, 'name' => 'Kalaat El Andalous'],
            ['id' => 6, 'state_id' => 1, 'name' => 'Ettadhamen-Mnihla'],
            ['id' => 7, 'state_id' => 2, 'name' => 'Testour'],
            ['id' => 8, 'state_id' => 2, 'name' => 'El Maagoula'],
            ['id' => 9, 'state_id' => 2, 'name' => 'Zahret Median'],
            ['id' => 10, 'state_id' => 2, 'name' => 'Nefza'],
            ['id' => 11, 'state_id' => 2, 'name' => 'Téboursouk'],
            ['id' => 12, 'state_id' => 2, 'name' => 'Goubellet'],
            ['id' => 13, 'state_id' => 2, 'name' => 'Majaz Al Beb'],
            ['id' => 14, 'state_id' => 2, 'name' => 'Béja'],
            ['id' => 15, 'state_id' => 3, 'name' => 'Bizerte'],
            ['id' => 16, 'state_id' => 3, 'name' => 'Sejnane'],
            ['id' => 17, 'state_id' => 3, 'name' => 'Mateur'],
            ['id' => 18, 'state_id' => 3, 'name' => 'Menzel Bourgibe'],
            ['id' => 19, 'state_id' => 3, 'name' => 'Tinja'],
            ['id' => 20, 'state_id' => 3, 'name' => 'Aousja'],
            ['id' => 21, 'state_id' => 3, 'name' => 'Menzel Jemil'],
            ['id' => 22, 'state_id' => 3, 'name' => 'Menzel Abderrahmen'],
            ['id' => 23, 'state_id' => 3, 'name' => 'El Alia'],
            ['id' => 24, 'state_id' => 3, 'name' => 'Ras Jebel'],
            ['id' => 25, 'state_id' => 3, 'name' => 'Metline'],
            ['id' => 26, 'state_id' => 3, 'name' => 'Raf Raf'],
            ['id' => 27, 'state_id' => 4, 'name' => 'Ben Arous'],
            ['id' => 28, 'state_id' => 4, 'name' => 'El Mourouj'],
            ['id' => 29, 'state_id' => 4, 'name' => 'Hammam Lif'],
            ['id' => 30, 'state_id' => 4, 'name' => 'Hammam Chott'],
            ['id' => 31, 'state_id' => 4, 'name' => 'Bou Mhel El-Bassatine'],
            ['id' => 32, 'state_id' => 4, 'name' => 'Ezzahra'],
            ['id' => 33, 'state_id' => 4, 'name' => 'Radès'],
            ['id' => 34, 'state_id' => 4, 'name' => 'Mègrine'],
            ['id' => 35, 'state_id' => 4, 'name' => 'Khalidia'],
            ['id' => 36, 'state_id' => 4, 'name' => 'Morneg'],
            ['id' => 37, 'state_id' => 4, 'name' => 'Mohamedia_Fouchana'],
            ['id' => 38, 'state_id' => 5, 'name' => 'Gabès'],
            ['id' => 39, 'state_id' => 5, 'name' => 'Chenini Nahal'],
            ['id' => 40, 'state_id' => 5, 'name' => 'Ghannouch'],
            ['id' => 41, 'state_id' => 5, 'name' => 'Métouia'],
            ['id' => 42, 'state_id' => 5, 'name' => 'Oudhref'],
            ['id' => 43, 'state_id' => 5, 'name' => 'El Hamma'],
            ['id' => 44, 'state_id' => 5, 'name' => 'Matmata'],
            ['id' => 45, 'state_id' => 5, 'name' => 'Nouvelle Matmata'],
            ['id' => 46, 'state_id' => 5, 'name' => 'Mareth'],
            ['id' => 47, 'state_id' => 5, 'name' => 'Zarat'],
            ['id' => 48, 'state_id' => 6, 'name' => 'Gafsa'],
            ['id' => 49, 'state_id' => 6, 'name' => 'El Ksar'],
            ['id' => 50, 'state_id' => 6, 'name' => 'Moularès'],

            ['id' => 51, 'state_id' => 6, 'name' => 'Redheyef'],
            ['id' => 52, 'state_id' => 6, 'name' => 'Métlaoui'],
            ['id' => 53, 'state_id' => 6, 'name' => 'Mdhila'],
            ['id' => 54, 'state_id' => 6, 'name' => 'El Guettar'],
            ['id' => 55, 'state_id' => 6, 'name' => 'Sened'],
            ['id' => 56, 'state_id' => 7, 'name' => 'Jendouba'],
            ['id' => 57, 'state_id' => 7, 'name' => 'Bou Salem'],
            ['id' => 58, 'state_id' => 7, 'name' => 'Tabarka'],
            ['id' => 59, 'state_id' => 7, 'name' => 'Aïn Drahem'],
            ['id' => 60, 'state_id' => 7, 'name' => 'Fernana'],
            ['id' => 61, 'state_id' => 7, 'name' => 'Beni MTir'],
            ['id' => 62, 'state_id' => 7, 'name' => 'Ghardimaou'],
            ['id' => 63, 'state_id' => 7, 'name' => 'Oued Melliz'],
            ['id' => 64, 'state_id' => 8, 'name' => 'Kebili'],
            ['id' => 65, 'state_id' => 8, 'name' => 'Djemna'],
            ['id' => 66, 'state_id' => 8, 'name' => 'Douz'],
            ['id' => 67, 'state_id' => 8, 'name' => 'El Golaa'],
            ['id' => 68, 'state_id' => 8, 'name' => 'Souk Lahad'],
            ['id' => 69, 'state_id' => 9, 'name' => 'Kairouan'],
            ['id' => 70, 'state_id' => 9, 'name' => 'Chebika'],
            ['id' => 71, 'state_id' => 9, 'name' => 'Sbikha'],
            ['id' => 72, 'state_id' => 9, 'name' => 'Oueslatia'],
            ['id' => 73, 'state_id' => 9, 'name' => 'Gammarth'],
            ['id' => 74, 'state_id' => 9, 'name' => 'Gammarth'],
            ['id' => 75, 'state_id' => 9, 'name' => 'Aïn Djeloula'],
            ['id' => 76, 'state_id' => 9, 'name' => 'Haffouz'],
            ['id' => 77, 'state_id' => 9, 'name' => 'Alaa'],
            ['id' => 78, 'state_id' => 9, 'name' => 'Hajeb El Ayoun'],
            ['id' => 79, 'state_id' => 9, 'name' => 'Nasrallah'],
            ['id' => 80, 'state_id' => 9, 'name' => 'Menzel Mehiri'],
            ['id' => 81, 'state_id' => 9, 'name' => 'Echrarda'],
            ['id' => 82, 'state_id' => 9, 'name' => 'Bou hajla'],
            ['id' => 83, 'state_id' => 10, 'name' => 'Haïdra'],
            ['id' => 84, 'state_id' => 10, 'name' => 'Kasserine'],
            ['id' => 85, 'state_id' => 10, 'name' => 'Sbitla'],
            ['id' => 86, 'state_id' => 10, 'name' => 'Magel Bel Abbès'],
            ['id' => 87, 'state_id' => 10, 'name' => 'Thélepte'],
            ['id' => 88, 'state_id' => 10, 'name' => 'Fériana'],
            ['id' => 89, 'state_id' => 10, 'name' => 'Foussana'],
            ['id' => 90, 'state_id' => 10, 'name' => 'Thala'],
            ['id' => 91, 'state_id' => 10, 'name' => 'Jedelienne'],
            ['id' => 92, 'state_id' => 11, 'name' => 'El Kef'],
            ['id' => 93, 'state_id' => 11, 'name' => 'Sers'],
            ['id' => 94, 'state_id' => 11, 'name' => 'Dahmani'],
            ['id' => 95, 'state_id' => 11, 'name' => 'El Ksour'],
            ['id' => 96, 'state_id' => 11, 'name' => 'Jérissa'],
            ['id' => 97, 'state_id' => 11, 'name' => 'Kalâat Khasba'],
            ['id' => 98, 'state_id' => 11, 'name' => 'Kalaat es Senam'],
            ['id' => 99, 'state_id' => 11, 'name' => 'Menzel Salem'],
            ['id' => 100, 'state_id' => 11, 'name' => 'Tajerouine'],

            ['id' => 101, 'state_id' => 11, 'name' => 'Sakiet Sidi Youssef'],
            ['id' => 102, 'state_id' => 11, 'name' => 'Touiref'],
            ['id' => 103, 'state_id' => 11, 'name' => 'Nebeur'],
            ['id' => 104, 'state_id' => 12, 'name' => 'Medenine'],
            ['id' => 105, 'state_id' => 12, 'name' => 'Ajim'],
            ['id' => 106, 'state_id' => 12, 'name' => 'Midoun'],
            ['id' => 107, 'state_id' => 12, 'name' => 'Houmt El Souk'],
            ['id' => 108, 'state_id' => 12, 'name' => 'Zarzis'],
            ['id' => 109, 'state_id' => 12, 'name' => 'Ben Gardane'],
            ['id' => 110, 'state_id' => 12, 'name' => 'Beni Khedache'],
            ['id' => 111, 'state_id' => 13, 'name' => 'Mahdia'],
            ['id' => 112, 'state_id' => 13, 'name' => 'El Bradâa'],
            ['id' => 113, 'state_id' => 13, 'name' => 'Ksour Essef'],
            ['id' => 114, 'state_id' => 13, 'name' => 'Sidi Alouane'],
            ['id' => 115, 'state_id' => 13, 'name' => 'Melloulèche'],
            ['id' => 116, 'state_id' => 13, 'name' => 'Chebba'],
            ['id' => 117, 'state_id' => 13, 'name' => 'Kerker'],
            ['id' => 118, 'state_id' => 13, 'name' => 'El Djem'],
            ['id' => 119, 'state_id' => 13, 'name' => 'Essouassi'],
            ['id' => 120, 'state_id' => 13, 'name' => 'Hebira'],
            ['id' => 121, 'state_id' => 13, 'name' => 'Chorbane'],
            ['id' => 122, 'state_id' => 13, 'name' => 'Ouled Chamekh'],
            ['id' => 123, 'state_id' => 13, 'name' => 'Bou Merdes'],
            ['id' => 124, 'state_id' => 13, 'name' => 'Rejiche'],
            ['id' => 125, 'state_id' => 14, 'name' => 'Manouba'],
            ['id' => 126, 'state_id' => 14, 'name' => 'Den Den'],
            ['id' => 127, 'state_id' => 14, 'name' => 'Douar Hicheق'],
            ['id' => 128, 'state_id' => 14, 'name' => 'Oued Ellil'],
            ['id' => 129, 'state_id' => 14, 'name' => 'Mornaguia'],
            ['id' => 130, 'state_id' => 14, 'name' => 'Borj El Amri'],
            ['id' => 131, 'state_id' => 14, 'name' => 'Djedeida'],
            ['id' => 132, 'state_id' => 14, 'name' => 'Tebourba'],
            ['id' => 133, 'state_id' => 14, 'name' => 'El Battan'],
            ['id' => 134, 'state_id' => 15, 'name' => 'Monastir'],
            ['id' => 135, 'state_id' => 15, 'name' => 'moknine'],
            ['id' => 136, 'state_id' => 15, 'name' => 'Beni Hassen'],
            ['id' => 137, 'state_id' => 15, 'name' => 'Khniss'],
            ['id' => 138, 'state_id' => 15, 'name' => 'Téboulba'],
            ['id' => 139, 'state_id' => 15, 'name' => 'Bekalta'],
            ['id' => 140, 'state_id' => 15, 'name' => 'Zéramdine'],
            ['id' => 141, 'state_id' => 15, 'name' => 'Lemta'],
            ['id' => 142, 'state_id' => 15, 'name' => 'Sayada'],
            ['id' => 143, 'state_id' => 15, 'name' => 'Jemmal'],
            ['id' => 144, 'state_id' => 15, 'name' => 'Sahline Moôtmar'],
            ['id' => 145, 'state_id' => 15, 'name' => 'Ouerdanin'],
            ['id' => 146, 'state_id' => 15, 'name' => 'Menzel Hayet'],
            ['id' => 147, 'state_id' => 15, 'name' => 'Bouhjar'],
            ['id' => 148, 'state_id' => 15, 'name' => 'Touza'],
            ['id' => 149, 'state_id' => 15, 'name' => 'Benen Bodher'],
            ['id' => 150, 'state_id' => 15, 'name' => 'Ksibet El Mediouni'],

            ['id' => 151, 'state_id' => 15, 'name' => 'Ksar Hellal'],
            ['id' => 152, 'state_id' => 15, 'name' => 'Cherahil'],
            ['id' => 153, 'state_id' => 15, 'name' => 'Menzel Farsi'],
            ['id' => 154, 'state_id' => 15, 'name' => 'Sidi Bennour'],
            ['id' => 155, 'state_id' => 15, 'name' => 'El Masdour'],
            ['id' => 156, 'state_id' => 15, 'name' => 'Menzel Ennour'],
            ['id' => 157, 'state_id' => 15, 'name' => 'Bembla-Mnara'],
            ['id' => 158, 'state_id' => 15, 'name' => 'Zaouiet Kontoch'],
            ['id' => 159, 'state_id' => 15, 'name' => 'Menzel Kamel'],
            ['id' => 160, 'state_id' => 15, 'name' => 'Ghenada'],
            ['id' => 161, 'state_id' => 15, 'name' => 'Amiret El Hojjaj'],
            ['id' => 162, 'state_id' => 15, 'name' => 'Amiret Touazra'],
            ['id' => 163, 'state_id' => 15, 'name' => 'Amiret El Fhoul'],
            ['id' => 164, 'state_id' => 15, 'name' => 'Sidi Ameur'],
            ['id' => 165, 'state_id' => 16, 'name' => 'Nabeul'],
            ['id' => 166, 'state_id' => 16, 'name' => 'Hammamet'],
            ['id' => 167, 'state_id' => 16, 'name' => 'Dar Chaabane'],
            ['id' => 168, 'state_id' => 16, 'name' => 'Béni Khiar'],
            ['id' => 169, 'state_id' => 16, 'name' => 'El Maâmoura'],
            ['id' => 170, 'state_id' => 16, 'name' => 'Somâa'],
            ['id' => 171, 'state_id' => 16, 'name' => 'Korba'],
            ['id' => 172, 'state_id' => 16, 'name' => 'Tazerka'],
            ['id' => 173, 'state_id' => 16, 'name' => 'Menzel Temime'],
            ['id' => 174, 'state_id' => 16, 'name' => 'Menzel Horr'],
            ['id' => 175,'state_id' => 16, 'name' => 'El Mida'],
            ['id' => 176, 'state_id' => 16, 'name' => 'Kelibia'],
            ['id' => 177, 'state_id' => 16, 'name' => 'Azmour'],
            ['id' => 178, 'state_id' => 16, 'name' => 'Hammam Ghezèze'],
            ['id' => 179, 'state_id' => 16, 'name' => 'Dar Allouch'],
            ['id' => 180, 'state_id' => 16, 'name' => 'El Haouaria'],
            ['id' => 181, 'state_id' => 16, 'name' => 'Takelsa'],
            ['id' => 182, 'state_id' => 16, 'name' => 'Soliman'],
            ['id' => 183, 'state_id' => 16, 'name' => 'Korbous'],
            ['id' => 184, 'state_id' => 16, 'name' => 'Menzel Bouzelfa'],
            ['id' => 185, 'state_id' => 16, 'name' => 'Béni Khalled'],
            ['id' => 186, 'state_id' => 16, 'name' => 'Zaouiet Djedidi'],
            ['id' => 187, 'state_id' => 16, 'name' => 'Grombalia'],
            ['id' => 188, 'state_id' => 16, 'name' => 'Bou Argoub'],
            ['id' => 189, 'state_id' => 17, 'name' => 'Sfax'],
            ['id' => 190, 'state_id' => 17, 'name' => 'Kerkennah'],
            ['id' => 191, 'state_id' => 17, 'name' => 'Mahares'],
            ['id' => 192, 'state_id' => 17, 'name' => 'Skhira'],
            ['id' => 193, 'state_id' => 17, 'name' => 'Bir Ali Ben Khélifa'],
            ['id' => 194, 'state_id' => 17, 'name' => 'Ghraïba, Tunisia'],
            ['id' => 195, 'state_id' => 17, 'name' => 'Menzel Chaker'],
            ['id' => 196, 'state_id' => 17, 'name' => 'El Hencha'],
            ['id' => 197, 'state_id' => 17, 'name' => 'Jebiniana'],
            ['id' => 198, 'state_id' => 17, 'name' => 'Agareb'],
            ['id' => 199, 'state_id' => 17, 'name' => 'Thyna'],
            ['id' => 200, 'state_id' => 17, 'name' => 'El Ain'],

            ['id' => 201, 'state_id' => 17, 'name' => 'Gremda'],
            ['id' => 202, 'state_id' => 17, 'name' => 'Sakiet Eddaïer'],
            ['id' => 203, 'state_id' => 17, 'name' => 'Sakiet Ezzit'],
            ['id' => 204, 'state_id' => 18, 'name' => 'Sidi Bouzid'],
            ['id' => 205, 'state_id' => 18, 'name' => 'Jilma'],
            ['id' => 206, 'state_id' => 18, 'name' => 'Cebalet'],
            ['id' => 207, 'state_id' => 18, 'name' => 'Bir El Hafey'],
            ['id' => 208, 'state_id' => 18, 'name' => 'Sidi Ali Ben Aoun'],
            ['id' => 209, 'state_id' => 18, 'name' => 'Menzel Bouzaiane'],
            ['id' => 210, 'state_id' => 18, 'name' => 'Meknassy'],
            ['id' => 211, 'state_id' => 18, 'name' => 'Mezzouna'],
            ['id' => 212, 'state_id' => 18, 'name' => 'Regueb'],
            ['id' => 213, 'state_id' => 18, 'name' => 'Ouled Haffouz'],
            ['id' => 214, 'state_id' => 18, 'name' => ''],
            ['id' => 215, 'state_id' => 19, 'name' => 'Siliana'],
            ['id' => 216, 'state_id' => 19, 'name' => 'Bou Arada'],
            ['id' => 217, 'state_id' => 19, 'name' => 'Gaâfour'],
            ['id' => 218, 'state_id' => 19, 'name' => 'El Krib'],
            ['id' => 219, 'state_id' => 19, 'name' => 'Sidi Bou Rouis'],
            ['id' => 220, 'state_id' => 19, 'name' => 'Maktar'],
            ['id' => 221, 'state_id' => 19, 'name' => 'Rouhia'],
            ['id' => 222, 'state_id' => 19, 'name' => 'Kesra'],
            ['id' => 223, 'state_id' => 19, 'name' => 'Bargou'],
            ['id' => 224, 'state_id' => 19, 'name' => ' El Aroussa'],
            ['id' => 225, 'state_id' => 20, 'name' => 'Sousse'],
            ['id' => 226, 'state_id' => 20, 'name' => 'Ksibet Thrayet'],
            ['id' => 227, 'state_id' => 20, 'name' => 'Ezzouhour'],
            ['id' => 228, 'state_id' => 20, 'name' => 'Zaouiet Sousse'],
            ['id' => 229, 'state_id' => 20, 'name' => 'Hammam Sousse'],
            ['id' => 230, 'state_id' => 20, 'name' => 'Akouda'],
            ['id' => 231, 'state_id' => 20, 'name' => 'Kalâa Kebira'],
            ['id' => 232, 'state_id' => 20, 'name' => 'Sidi Bou Ali'],
            ['id' => 233, 'state_id' => 20, 'name' => 'Hergla'],
            ['id' => 234, 'state_id' => 20, 'name' => 'Enfidha'],
            ['id' => 235, 'state_id' => 20, 'name' => 'Bouficha'],
            ['id' => 236, 'state_id' => 20, 'name' => 'Sidi El Hani'],
            ['id' => 237, 'state_id' => 20, 'name' => 'Msaken'],
            ['id' => 238, 'state_id' => 20, 'name' => 'Kalâa Seghira'],
            ['id' => 239, 'state_id' => 20, 'name' => 'Messaadine'],
            ['id' => 240, 'state_id' => 20, 'name' => 'Kondar'],
            ['id' => 241, 'state_id' => 21, 'name' => 'Tataouine'],
            ['id' => 242, 'state_id' => 21, 'name' => 'Bir Lahmar'],
            ['id' => 243, 'state_id' => 21, 'name' => 'Ghomrassen'],
            ['id' => 244, 'state_id' => 21, 'name' => 'Dehiba'],
            ['id' => 245, 'state_id' => 21, 'name' => 'Remada'],
            ['id' => 246, 'state_id' => 22, 'name' => 'Tozeur'],
            ['id' => 247, 'state_id' => 22, 'name' => 'Degache'],
            ['id' => 248, 'state_id' => 22, 'name' => 'Hamet Jerid'],
            ['id' => 249, 'state_id' => 22, 'name' => 'Nafta'],
            ['id' => 250, 'state_id' => 22, 'name' => 'Tamerza'],
            
            ['id' => 251, 'state_id' => 23, 'name' => 'Tunis'],
            ['id' => 252, 'state_id' => 23, 'name' => 'Ariana'],
            ['id' => 253, 'state_id' => 23, 'name' => 'Sidi Hassine'],
            ['id' => 254, 'state_id' => 23, 'name' => 'La Marsa'],
            ['id' => 255, 'state_id' => 23, 'name' => 'Sidi Bou Said'],
            ['id' => 256, 'state_id' => 23, 'name' => 'Carthage'],
            ['id' => 257, 'state_id' => 23, 'name' => 'la Goulette'],
            ['id' => 258, 'state_id' => 23, 'name' => 'Le Kram'],
            ['id' => 259, 'state_id' => 23, 'name' => 'Le Bardo'],
            ['id' => 260, 'state_id' => 24, 'name' => 'Zaghouan'],
            ['id' => 261, 'state_id' => 24, 'name' => 'Zriba'],
            ['id' => 262, 'state_id' => 24, 'name' => 'Bir Mcherga'],
            ['id' => 263, 'state_id' => 24, 'name' => 'Djebel Oust'],
            ['id' => 264, 'state_id' => 24, 'name' => 'El Fahs'],
            ['id' => 265, 'state_id' => 24, 'name' => 'Nadhour'],
        ];

        foreach ($cities as $city) {
            LocationCity::factory()->create([
                'id' => $city['id'],
                'state_id' => $city['state_id'],
                'name' => $city['name'],
            ]);
        }
    }
}
